server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktb_hackathon
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:00000000}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      s3:
        access-key: ${AWS_S3_ACCESS_KEY:test-access-key}
        secret-key: ${AWS_S3_SECRET_KEY:test-secret-key}
        bucket: ${AWS_S3_BUCKET:test-bucket}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups.enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persistAuthorization: true